function esc(value) {
  return String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[c]));
}

function shell(title, body, script = "") {
  return `<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>
  :root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#090909;color:#f5f5f5;font-family:system-ui,-apple-system,sans-serif}.wrap{max-width:1040px;margin:auto;padding:22px}.card{background:#111;border:1px solid #2c2c2c;border-radius:18px;padding:18px;margin-bottom:16px}h1{margin:.2em 0}.muted{color:#aaa}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.fact{padding:12px;background:#171717;border-radius:12px}.fact span{display:block;font-size:12px}.status{display:inline-block;padding:5px 9px;border-radius:999px;background:#242424}.status.paid{background:#17351e}.status.pending{background:#3a3212}.status.cancelled,.status.failed,.status.expired{background:#3b1717}button,input,select{font:inherit}button{border:0;border-radius:10px;padding:10px 13px;cursor:pointer}button.danger{background:#6a2323;color:white}button.secondary{background:#2d2d2d;color:white}.toolbar{display:flex;gap:10px;flex-wrap:wrap;align-items:end}label{display:grid;gap:6px}input,select{background:#080808;border:1px solid #333;color:white;border-radius:10px;padding:10px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:850px}th,td{text-align:left;border-bottom:1px solid #2b2b2b;padding:10px;vertical-align:top}.actions{display:flex;gap:7px;flex-wrap:wrap}.ok{color:#8be59b}.error{color:#ff9c9c}.qr{display:block;max-width:330px;width:100%;margin:16px auto;background:white;padding:8px;border-radius:14px}.notice{padding:12px;border:1px solid #564d20;background:#211e10;border-radius:12px}
  </style></head><body><main class="wrap">${body}</main>${script ? `<script>${script}</script>` : ""}</body></html>`;
}

export function checkoutPage(orderId) {
  const id = esc(orderId);
  const script = `
  const id=${JSON.stringify(orderId)};const q=(s)=>document.querySelector(s);const money=(v)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v||0));
  const date=(v)=>v?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(Number(v)*1000)):'-';
  async function load(){try{const r=await fetch('/api/orders/'+encodeURIComponent(id),{cache:'no-store'});const x=await r.json();if(!r.ok||!x.ok)throw Error(x.error||'Gagal memuat order');const o=x.order;q('[data-amount]').textContent=money(o.unique_amount);q('[data-base]').textContent=money(o.base_amount);q('[data-source]').textContent=o.source;q('[data-status]').textContent=o.status;q('[data-status]').className='status '+o.status;q('[data-exp]').textContent=date(o.expires_at);if(['paid','expired','cancelled','failed'].includes(o.status))clearInterval(timer);}catch(e){q('[data-error]').textContent=e.message;q('[data-error]').className='error';}}
  load();const timer=setInterval(load,4000);`;
  return shell("Pembayaran QRIS", `<section class="card"><div class="muted">QRIS PAYMENT</div><h1>Bayar order ${id}</h1><img class="qr" src="/api/orders/${encodeURIComponent(orderId)}/qris" alt="QRIS"><div class="grid"><div class="fact"><span class="muted">Order</span><strong>${id}</strong></div><div class="fact"><span class="muted">Total bayar</span><strong data-amount>Memuat…</strong></div><div class="fact"><span class="muted">Nilai saldo</span><strong data-base>Memuat…</strong></div><div class="fact"><span class="muted">Sumber</span><strong data-source>Memuat…</strong></div><div class="fact"><span class="muted">Status</span><strong data-status class="status pending">pending</strong></div><div class="fact"><span class="muted">Kedaluwarsa</span><strong data-exp>Memuat…</strong></div></div><p class="notice">Bayar tepat sesuai <strong>Total bayar</strong>. Pembayaran tidak dideteksi otomatis; admin memeriksa mutasi merchant lalu menandai order sebagai paid.</p><div data-error></div></section>`, script);
}

export function adminPaymentsPage() {
  const script = `
  const token=q('[data-token]'),filter=q('[data-filter]'),body=q('[data-orders]'),msg=q('[data-message]');function q(s){return document.querySelector(s)}const money=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v||0));const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const date=v=>v?new Date(Number(v)*1000).toLocaleString('id-ID'):'-';
  function headers(){const t=token.value.trim();if(!t)throw Error('Masukkan token admin.');return {'x-admin-token':t,'content-type':'application/json'}}
  async function call(path,opt={}){const r=await fetch(path,{cache:'no-store',...opt,headers:{...headers(),...(opt.headers||{})}});const x=await r.json();if(!r.ok||!x.ok)throw Error(x.error||'Permintaan gagal');return x}
  function render(list){body.innerHTML=list.length?list.map(o=>{const cust=[o.customer_name,o.username?'@'+o.username:'',o.email].filter(Boolean).map(esc).join('<br>')||'-';const actions=o.status==='pending'?'<button data-a="paid" data-id="'+esc(o.id)+'">Mark paid</button><button class="danger" data-a="cancel" data-id="'+esc(o.id)+'">Cancel</button>':o.status==='paid'&&o.settlement_status!=='delivered'?'<button class="secondary" data-a="retry" data-id="'+esc(o.id)+'">Retry webhook</button>':'—';return '<tr><td><strong>'+esc(o.id)+'</strong><br><span class="muted">'+esc(o.reference)+'</span></td><td>'+esc(o.source)+'<br>'+cust+'</td><td>'+money(o.base_amount)+'<br><strong>'+money(o.unique_amount)+'</strong></td><td><span class="status '+esc(o.status)+'">'+esc(o.status)+'</span><br><span class="muted">'+esc(o.settlement_status)+'</span></td><td>'+date(o.created_at)+'<br>'+date(o.expires_at)+'</td><td class="actions">'+actions+'</td></tr>'}).join(''):'<tr><td colspan="6" class="muted">Tidak ada order.</td></tr>'}
  async function load(){msg.textContent='';try{render((await call('/api/admin/payments?status='+encodeURIComponent(filter.value))).orders)}catch(e){msg.className='error';msg.textContent=e.message}}
  body.addEventListener('click',async e=>{const b=e.target.closest('button[data-a]');if(!b)return;const id=b.dataset.id,a=b.dataset.a;if(a==='paid'&&!confirm('Pastikan mutasi merchant sudah masuk. Tandai PAID?'))return;if(a==='cancel'&&!confirm('Batalkan order '+id+'?'))return;b.disabled=true;try{const path=a==='paid'?'/api/admin/payments/'+encodeURIComponent(id)+'/mark-paid':a==='cancel'?'/api/admin/payments/'+encodeURIComponent(id)+'/cancel':'/api/admin/payments/'+encodeURIComponent(id)+'/retry-webhook';const x=await call(path,{method:'POST'});msg.className=x.settlement?.settlement_status==='retry_needed'?'error':'ok';msg.textContent=x.settlement?.settlement_status==='retry_needed'?'Order paid, webhook perlu retry.':'Berhasil.';await load()}catch(err){msg.className='error';msg.textContent=err.message;b.disabled=false}});q('[data-load]').onclick=load;q('[data-refresh]').onclick=load;filter.onchange=load;`;
  return shell("Admin Payments", `<section class="card"><div class="muted">QRIS PAYMENT GATEWAY / ADMIN</div><h1>Payment dashboard</h1><p>Token admin hanya berada di memori halaman selama tab terbuka; tidak disimpan ke localStorage atau sessionStorage.</p><div class="toolbar"><label>Admin token<input data-token type="password" autocomplete="off" placeholder="QRIS_ADMIN_TOKEN"></label><label>Status<select data-filter><option value="all">Semua</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="expired">Expired</option><option value="cancelled">Cancelled</option><option value="failed">Failed</option></select></label><button data-load>Load</button><button class="secondary" data-refresh>Refresh</button></div><div data-message></div></section><section class="card"><div class="table-wrap"><table><thead><tr><th>Order</th><th>Source / customer</th><th>Base / total</th><th>Status</th><th>Created / expires</th><th>Action</th></tr></thead><tbody data-orders><tr><td colspan="6" class="muted">Masukkan token admin lalu Load.</td></tr></tbody></table></div></section>`, script);
}
